import { z } from 'zod'
import type { MarketMessage } from '../types/market'

const CandleSchema = z.object({
  timestamp: z.number().int().positive(),
  open: z.number().positive(),
  high: z.number().positive(),
  low: z.number().positive(),
  close: z.number().positive(),
  volume: z.number().nonnegative(),
  is_closed: z.boolean(),
})

const MessageSchema = z.union([
  z.object({
    update_type: z.literal('snapshot'),
    symbol: z.string().optional(),
    timeframe: z.string().optional(),
    candles: z.array(CandleSchema),
    swings: z.array(z.object({
      timestamp: z.number(),
      price: z.number(),
      kind: z.enum(['high', 'low']),
      index: z.number(),
    })).optional(),
    structure: z.array(z.object({
      timestamp: z.number(),
      price: z.number(),
      kind: z.enum(['HH', 'HL', 'LH', 'LL', 'BOS', 'CHoCH']),
      broken_swing_price: z.number(),
      direction: z.enum(['bullish', 'bearish']).nullable().optional(),
    })).optional(),
    fvgs: z.array(z.object({
      id: z.string(),
      top: z.number(),
      bottom: z.number(),
      timestamp: z.number(),
      direction: z.enum(['bullish', 'bearish']),
      is_filled: z.boolean(),
      fill_timestamp: z.number().nullable().optional(),
    })).optional(),
    order_blocks: z.array(z.object({
      id: z.string(),
      top: z.number(),
      bottom: z.number(),
      timestamp: z.number(),
      direction: z.enum(['bullish', 'bearish']),
      is_breaker: z.boolean(),
      breaker_timestamp: z.number().nullable().optional(),
    })).optional(),
    liquidity: z.array(z.object({
      id: z.string(),
      price: z.number(),
      kind: z.enum(['equal_high', 'equal_low']),
      touch_count: z.number(),
      first_touch_timestamp: z.number().nullable().optional(),
      last_touch_timestamp: z.number().nullable().optional(),
      swept: z.boolean(),
      sweep_timestamp: z.number().nullable().optional(),
    })).optional(),
    liquidity_events: z.array(z.object({
      id: z.string(),
      timestamp: z.number(),
      side: z.enum(['buy_side', 'sell_side']),
      swept_level: z.number(),
      sweep_price: z.number(),
      close_price: z.number(),
      sweep_depth: z.number(),
      displacement: z.number(),
      reclaimed: z.boolean(),
      engineered_score: z.number(),
      reason: z.string(),
    })).optional(),
    signals: z.array(z.object({
      id: z.string(),
      timestamp: z.number(),
      side: z.enum(['buy', 'sell']),
      entry: z.number(),
      stop_loss: z.number(),
      trailing_stop: z.number().nullable().optional(),
      trailing_mode: z.string().optional(),
      exit_price: z.number(),
      risk_reward: z.number(),
      confidence: z.number(),
      reason: z.string(),
      status: z.enum(['pending', 'open', 'target_hit', 'stopped']),
      exit_timestamp: z.number().nullable().optional(),
      institutional_score: z.number(),
      liquidity_score: z.number(),
      bias_score: z.number(),
      expected_move: z.number(),
      win_probability: z.number().optional(),
      kelly_fraction: z.number().optional(),
      suggested_risk_fraction: z.number().optional(),
      cvar95_loss: z.number().optional(),
      risk_of_ruin: z.number().optional(),
      model: z.string(),
    })).optional(),
    metrics: z.object({
      timestamp: z.number(),
      atr14: z.number(),
      ema20: z.number(),
      ema50: z.number(),
      rsi14: z.number(),
      vwap: z.number(),
      vwap_distance_pct: z.number(),
      volume_zscore: z.number(),
      realized_volatility: z.number(),
      parkinson_volatility: z.number(),
      garman_klass_volatility: z.number(),
      displacement_ratio: z.number(),
      premium_discount: z.number(),
      equilibrium: z.number(),
      range_high: z.number(),
      range_low: z.number(),
      trend_score: z.number(),
      volatility_score: z.number(),
      institutional_bias: z.enum(['bullish', 'bearish', 'neutral']),
      bias_score: z.number(),
      expected_move: z.number(),
      expected_move_pct: z.number(),
    }).nullable().optional(),
    projection: z.object({
      timestamp: z.number(),
      direction: z.enum(['bullish', 'bearish', 'neutral']),
      probability: z.number(),
      expected_move: z.number(),
      expected_high: z.number(),
      expected_low: z.number(),
      invalidation: z.number(),
      score: z.number(),
      reason: z.string(),
    }).nullable().optional(),
    regime: z.object({
      timestamp: z.number(),
      phase: z.enum(['trending', 'range_bound', 'consolidation', 'accumulation', 'distribution']),
      confidence: z.number(),
      range_high: z.number(),
      range_low: z.number(),
      range_mid: z.number(),
      width_pct: z.number(),
      atr_compression: z.number(),
      efficiency_ratio: z.number(),
      volume_state: z.enum(['compressed', 'normal', 'expanding']),
      bias: z.enum(['bullish', 'bearish', 'neutral']),
      reason: z.string(),
    }).nullable().optional(),
    options_context: z.object({
      timestamp: z.number(),
      underlying: z.string(),
      momentum_score: z.number(),
      bullish_momentum_score: z.number(),
      bearish_momentum_score: z.number(),
      minimum_momentum_score: z.number(),
      momentum_state: z.enum(['high', 'low']),
      call_candidate: z.object({
        symbol: z.string(),
        product_id: z.number().nullable().optional(),
        contract_type: z.string(),
        side: z.enum(['call', 'put']),
        strike_price: z.number(),
        expiry: z.string().nullable().optional(),
        expiry_timestamp: z.number().nullable().optional(),
        spot_price: z.number().nullable().optional(),
        mark_price: z.number().nullable().optional(),
        best_bid: z.number().nullable().optional(),
        best_ask: z.number().nullable().optional(),
        mid_price: z.number().nullable().optional(),
        spread_pct: z.number().nullable().optional(),
        bid_iv: z.number().nullable().optional(),
        ask_iv: z.number().nullable().optional(),
        volume: z.number().nullable().optional(),
        open_interest: z.number().nullable().optional(),
        delta: z.number().nullable().optional(),
        gamma: z.number().nullable().optional(),
        theta: z.number().nullable().optional(),
        vega: z.number().nullable().optional(),
        rho: z.number().nullable().optional(),
        score: z.number(),
        qualified: z.boolean(),
        reason: z.string(),
      }).nullable().optional(),
      put_candidate: z.object({
        symbol: z.string(),
        product_id: z.number().nullable().optional(),
        contract_type: z.string(),
        side: z.enum(['call', 'put']),
        strike_price: z.number(),
        expiry: z.string().nullable().optional(),
        expiry_timestamp: z.number().nullable().optional(),
        spot_price: z.number().nullable().optional(),
        mark_price: z.number().nullable().optional(),
        best_bid: z.number().nullable().optional(),
        best_ask: z.number().nullable().optional(),
        mid_price: z.number().nullable().optional(),
        spread_pct: z.number().nullable().optional(),
        bid_iv: z.number().nullable().optional(),
        ask_iv: z.number().nullable().optional(),
        volume: z.number().nullable().optional(),
        open_interest: z.number().nullable().optional(),
        delta: z.number().nullable().optional(),
        gamma: z.number().nullable().optional(),
        theta: z.number().nullable().optional(),
        vega: z.number().nullable().optional(),
        rho: z.number().nullable().optional(),
        score: z.number(),
        qualified: z.boolean(),
        reason: z.string(),
      }).nullable().optional(),
      blockers: z.array(z.string()),
      source_count: z.number(),
      error: z.string().nullable().optional(),
    }).nullable().optional(),
    sentiment: z.object({
      label: z.enum(['loading', 'bullish', 'bearish', 'neutral', 'unavailable']),
      score: z.number(),
      confidence: z.number(),
      source_count: z.number(),
      updated_at: z.number().nullable().optional(),
      headlines: z.array(z.object({
        title: z.string(),
        source: z.string(),
        url: z.string(),
        published_at: z.number().nullable().optional(),
        score: z.number(),
      })),
      provider: z.enum(['gemini', 'openai', 'local_keyword']),
      model: z.string().nullable().optional(),
      summary: z.string(),
      drivers: z.array(z.string()),
      risk_flags: z.array(z.string()),
      error: z.string().nullable().optional(),
    }).nullable().optional(),
    ai_ict: z.object({
      timestamp: z.number(),
      timeframe: z.string(),
      provider: z.enum(['gemini', 'deterministic']),
      model: z.string().nullable().optional(),
      direction: z.enum(['bullish', 'bearish', 'neutral']),
      grade: z.enum(['A+', 'A', 'B', 'C', 'NO_TRADE']),
      readiness: z.enum(['premium', 'qualified', 'watchlist', 'avoid']),
      confidence: z.number(),
      setup_score: z.number(),
      entry: z.number().nullable().optional(),
      stop_loss: z.number().nullable().optional(),
      take_profit: z.number().nullable().optional(),
      risk_reward: z.number().nullable().optional(),
      invalidation: z.number().nullable().optional(),
      primary_signal_id: z.string().nullable().optional(),
      summary: z.string(),
      option_contract: z.any().optional(), // Complex, skip for now
      momentum_score: z.number().nullable().optional(),
      options_score: z.number().nullable().optional(),
      confirmations: z.array(z.string()),
      blockers: z.array(z.string()),
      calculations: z.array(z.string()),
      guarantee: z.string(),
      updated_at: z.number().nullable().optional(),
      error: z.string().nullable().optional(),
    }).nullable().optional(),
    stats: z.object({
      closed_candles: z.number(),
      active_fvgs: z.number(),
      active_order_blocks: z.number(),
      active_liquidity: z.number(),
      liquidity_events: z.number(),
      signals: z.number(),
    }).optional(),
    available_timeframes: z.array(z.string()).optional(),
  }),
  z.object({ update_type: z.literal('tick'), candle: CandleSchema }),
  z.object({ update_type: z.literal('close'), candle: CandleSchema }),
  z.object({ update_type: z.literal('status'), status: z.string(), message: z.string().optional(), retry_in_seconds: z.number().optional() }),
  z.object({ update_type: z.literal('sentiment'), sentiment: z.any() }), // Simplified
  z.object({ update_type: z.literal('ai_ict'), ai_ict: z.any() }), // Simplified
  z.object({ update_type: z.literal('quote'), quote: z.any() }), // Simplified
  z.object({ update_type: z.literal('options_context'), options_context: z.any() }), // Simplified
])

export function parseMarketMessage(value: unknown): MarketMessage | null {
  const result = MessageSchema.safeParse(value)
  if (result.success) {
    return result.data as MarketMessage
  }
  console.warn('Invalid market message:', result.error, value)
  return null
}
