import { z } from 'zod'
import type { MarketMessage } from '../types/market'

const CandleSchema = z.object({
  timestamp: z.number().int().positive(),
  open: z.number().positive(),
  high: z.number().positive(),
  low: z.number().positive(),
  close: z.number().positive(),
  volume: z.number().nonnegative(),
  is_closed: z.boolean(),
})

const OrderbookImbalanceSchema = z.object({
  id: z.string(),
  timestamp: z.number(),
  price_level: z.number(),
  imbalance_ratio: z.number(),
  side: z.enum(['buy', 'sell']),
  strength: z.number(),
  duration_ms: z.number(),
  status: z.enum(['active', 'reversed', 'filled']),
  reversal_timestamp: z.number().nullable().optional(),
  reversal_price: z.number().nullable().optional(),
})

const SpreadDynamicsSchema = z.object({
  id: z.string(),
  timestamp: z.number(),
  spread: z.number(),
  spread_pct: z.number(),
  spread_zscore: z.number(),
  bid: z.number(),
  ask: z.number(),
  bid_ask_midpoint: z.number(),
  status: z.enum(['normal', 'tight', 'wide', 'squeezed']),
  anomaly_type: z.enum(['compression', 'expansion', 'inversion']).nullable().optional(),
})

const OrderbookDepthLevelSchema = z.object({
  id: z.string(),
  timestamp: z.number(),
  price_level: z.number(),
  level_type: z.enum(['bid', 'ask']),
  estimated_size: z.number(),
  order_count: z.number(),
  depth_tier: z.number(),
  saturation: z.number(),
  touched_count: z.number().optional(),
  last_touch: z.number().nullable().optional(),
  filled_count: z.number().optional(),
})

const OrderbookAccumulationSchema = z.object({
  id: z.string(),
  timestamp: z.number(),
  price_range_low: z.number(),
  price_range_high: z.number(),
  side: z.enum(['accumulation', 'distribution']),
  confidence: z.number(),
  volume_ratio: z.number(),
  pattern_duration_ms: z.number(),
  candle_touches: z.number(),
  status: z.enum(['active', 'completed']),
  completion_timestamp: z.number().nullable().optional(),
  completion_price: z.number().nullable().optional(),
})

const OrderbookDataSchema = z.object({
  imbalances: z.array(OrderbookImbalanceSchema),
  spread_dynamics: z.array(SpreadDynamicsSchema),
  depth_levels: z.array(OrderbookDepthLevelSchema),
  accumulations: z.array(OrderbookAccumulationSchema),
})

const MessageSchema = z.union([
  z.object({
    update_type: z.literal('snapshot'),
    symbol: z.string().optional(),
    timeframe: z.string().optional(),
    candles: z.array(CandleSchema),
    swings: z.array(z.object({
      timestamp: z.number(),
      price: z.number(),
      kind: z.enum(['high', 'low']),
      index: z.number(),
    })).optional(),
    structure: z.array(z.object({
      timestamp: z.number(),
      price: z.number(),
      kind: z.enum(['HH', 'HL', 'LH', 'LL', 'BOS', 'CHoCH']),
      broken_swing_price: z.number(),
      direction: z.enum(['bullish', 'bearish']).nullable().optional(),
    })).optional(),
    fvgs: z.array(z.object({
      id: z.string(),
      top: z.number(),
      bottom: z.number(),
      timestamp: z.number(),
      direction: z.enum(['bullish', 'bearish']),
      is_filled: z.boolean(),
      fill_timestamp: z.number().nullable().optional(),
    })).optional(),
    order_blocks: z.array(z.object({
      id: z.string(),
      top: z.number(),
      bottom: z.number(),
      timestamp: z.number(),
      direction: z.enum(['bullish', 'bearish']),
      is_breaker: z.boolean(),
      breaker_timestamp: z.number().nullable().optional(),
    })).optional(),
    liquidity: z.array(z.object({
      id: z.string(),
      price: z.number(),
      kind: z.enum(['equal_high', 'equal_low']),
      touch_count: z.number(),
      first_touch_timestamp: z.number().nullable().optional(),
      last_touch_timestamp: z.number().nullable().optional(),
      swept: z.boolean(),
      sweep_timestamp: z.number().nullable().optional(),
    })).optional(),
    liquidity_events: z.array(z.object({
      id: z.string(),
      timestamp: z.number(),
      side: z.enum(['buy_side', 'sell_side']),
      swept_level: z.number(),
      sweep_price: z.number(),
      close_price: z.number(),
      sweep_depth: z.number(),
      displacement: z.number(),
      reclaimed: z.boolean(),
      engineered_score: z.number(),
      reason: z.string(),
    })).optional(),
    signals: z.array(z.object({
      id: z.string(),
      timestamp: z.number(),
      side: z.enum(['buy', 'sell', 'long', 'short']),
      entry: z.number(),
      stop_loss: z.number(),
      trailing_stop: z.number().nullable().optional(),
      trailing_mode: z.string().optional(),
      exit_price: z.number(),
      risk_reward: z.number(),
      confidence: z.number(),
      reason: z.string(),
      status: z.enum(['pending', 'open', 'target_hit', 'stopped']),
      exit_timestamp: z.number().nullable().optional(),
      institutional_score: z.number(),
      liquidity_score: z.number(),
      bias_score: z.number(),
      expected_move: z.number(),
      win_probability: z.number().optional(),
      kelly_fraction: z.number().optional(),
      suggested_risk_fraction: z.number().optional(),
      cvar95_loss: z.number().optional(),
      risk_of_ruin: z.number().optional(),
      model: z.string(),
      garch_volatility: z.number().optional(),
      markov_regime: z.string().optional(),
      markov_certainty: z.number().optional(),
      monte_carlo_var95: z.number().optional(),
      signal_decay: z.number().optional(),
      bayesian_fused: z.boolean().optional(),
      bayesian_signal_count: z.number().optional(),
    })).optional(),
    metrics: z.object({
      timestamp: z.number(),
      atr14: z.number(),
      ema20: z.number(),
      ema50: z.number(),
      rsi14: z.number(),
      vwap: z.number(),
      vwap_distance_pct: z.number(),
      volume_zscore: z.number(),
      realized_volatility: z.number(),
      parkinson_volatility: z.number(),
      garman_klass_volatility: z.number(),
      displacement_ratio: z.number(),
      premium_discount: z.number(),
      equilibrium: z.number(),
      range_high: z.number(),
      range_low: z.number(),
      trend_score: z.number(),
      volatility_score: z.number(),
      institutional_bias: z.enum(['bullish', 'bearish', 'neutral']),
      bias_score: z.number(),
      expected_move: z.number(),
      expected_move_pct: z.number(),
      hurst_exponent: z.number().optional(),
      shannon_entropy: z.number().optional(),
      garch_volatility: z.number().optional(),
      garch_persistence: z.number().optional(),
      kalman_trend: z.number().optional(),
      kalman_trend_strength: z.number().optional(),
      markov_bull_prob: z.number().optional(),
      markov_bear_prob: z.number().optional(),
      markov_regime_certainty: z.number().optional(),
      monte_carlo_var95: z.number().optional(),
      monte_carlo_expected_return: z.number().optional(),
      monte_carlo_max_drawdown: z.number().optional(),
      fourier_dominant_period: z.number().optional(),
      fourier_cycle_strength: z.number().optional(),
      volume_profile_poc: z.number().optional(),
      volume_profile_vah: z.number().optional(),
      volume_profile_val: z.number().optional(),
      volume_profile_imbalance: z.number().optional(),
      return_skewness: z.number().optional(),
      return_kurtosis: z.number().optional(),
      fractal_dimension: z.number().optional(),
      ljung_box_statistic: z.number().optional(),
      autocorrelation_lag1: z.number().optional(),
    }).nullable().optional(),
    projection: z.object({
      timestamp: z.number(),
      direction: z.enum(['bullish', 'bearish', 'neutral']),
      probability: z.number(),
      expected_move: z.number(),
      expected_high: z.number(),
      expected_low: z.number(),
      invalidation: z.number(),
      score: z.number(),
      reason: z.string(),
    }).nullable().optional(),
    regime: z.object({
      timestamp: z.number(),
      phase: z.enum(['trending', 'range_bound', 'consolidation', 'accumulation', 'distribution']),
      confidence: z.number(),
      range_high: z.number(),
      range_low: z.number(),
      range_mid: z.number(),
      width_pct: z.number(),
      atr_compression: z.number(),
      efficiency_ratio: z.number(),
      volume_state: z.enum(['compressed', 'normal', 'expanding']),
      bias: z.enum(['bullish', 'bearish', 'neutral']),
      reason: z.string(),
    }).nullable().optional(),
    sentiment: z.object({
      label: z.enum(['loading', 'bullish', 'bearish', 'neutral', 'unavailable']),
      score: z.number(),
      confidence: z.number(),
      source_count: z.number(),
      updated_at: z.number().nullable().optional(),
      headlines: z.array(z.object({
        title: z.string(),
        source: z.string(),
        url: z.string(),
        published_at: z.number().nullable().optional(),
        score: z.number(),
      })),
      provider: z.enum(['gemini', 'openai', 'local_keyword']),
      model: z.string().nullable().optional(),
      summary: z.string(),
      drivers: z.array(z.string()),
      risk_flags: z.array(z.string()),
      error: z.string().nullable().optional(),
    }).nullable().optional(),
    ai_ict: z.object({
      timestamp: z.number(),
      timeframe: z.string(),
      provider: z.enum(['gemini', 'deterministic']),
      model: z.string().nullable().optional(),
      direction: z.enum(['bullish', 'bearish', 'neutral']),
      grade: z.enum(['A+', 'A', 'B', 'C', 'NO_TRADE']),
      readiness: z.enum(['premium', 'qualified', 'watchlist', 'avoid']),
      confidence: z.number(),
      setup_score: z.number(),
      entry: z.number().nullable().optional(),
      stop_loss: z.number().nullable().optional(),
      take_profit: z.number().nullable().optional(),
      risk_reward: z.number().nullable().optional(),
      invalidation: z.number().nullable().optional(),
      primary_signal_id: z.string().nullable().optional(),
      summary: z.string(),
      confirmations: z.array(z.string()),
      blockers: z.array(z.string()),
      calculations: z.array(z.string()),
      guarantee: z.string(),
      updated_at: z.number().nullable().optional(),
      error: z.string().nullable().optional(),
    }).nullable().optional(),
    scalp: z.any().nullable().optional(),
    scalp_risk: z.any().nullable().optional(),
    psychology: z.any().nullable().optional(),
    readability: z.any().nullable().optional(),
    orderbook: OrderbookDataSchema.optional(),
    stats: z.object({
      closed_candles: z.number(),
      signals: z.number(),
      scalp_signals: z.number().optional(),
      scalp_blocked: z.number().optional(),
      ob_imbalances: z.number().optional(),
      ob_spread_anomalies: z.number().optional(),
      ob_accumulations: z.number().optional(),
      btc_patterns: z.number().optional(),
      btc_behaviors: z.number().optional(),
      fear_greed: z.string().optional(),
      readability_grade: z.string().optional(),
      tradeability: z.string().optional(),
      ensemble: z.any().optional(),
      self_optimizer: z.any().optional(),
      anomaly_detector: z.any().optional(),
      system_health: z.any().optional(),
    }).passthrough().optional(),
    available_timeframes: z.array(z.string()).optional(),
    btc_patterns: z.any().nullable().optional(),
    paper_trading: z.object({
      total_trades: z.number(),
      closed_trades: z.number(),
      winning_trades: z.number(),
      losing_trades: z.number(),
      total_pnl: z.number(),
      win_rate: z.number(),
    }).optional(),
  }),
  z.object({ update_type: z.literal('tick'), candle: CandleSchema, quote: z.any().optional(), metrics: z.any().optional(), scalp: z.any().nullable().optional(), scalp_risk: z.any().nullable().optional(), psychology: z.any().nullable().optional(), readability: z.any().nullable().optional(), btc_patterns: z.any().nullable().optional() }).passthrough(),
  z.object({ update_type: z.literal('close'), candle: CandleSchema, quote: z.any().optional(), metrics: z.any().optional(), scalp: z.any().nullable().optional(), scalp_risk: z.any().nullable().optional(), psychology: z.any().nullable().optional(), readability: z.any().nullable().optional(), btc_patterns: z.any().nullable().optional() }).passthrough(),
  z.object({ update_type: z.literal('status'), status: z.string(), message: z.string().optional(), retry_in_seconds: z.number().optional(), symbol: z.string().optional(), timeframe: z.string().optional(), sentiment: z.any().optional(), ai_ict: z.any().optional(), available_timeframes: z.array(z.string()).optional() }).passthrough(),
  z.object({ update_type: z.literal('sentiment'), sentiment: z.any() }), // Simplified
  z.object({ update_type: z.literal('ai_ict'), ai_ict: z.any() }), // Simplified
  z.object({ update_type: z.literal('quote'), quote: z.any() }), // Simplified
  z.object({ update_type: z.literal('futures_context'), futures_context: z.any() }).passthrough(),
  z.object({ update_type: z.literal('alert') }).passthrough(),
])

export function parseMarketMessage(value: unknown): MarketMessage | null {
  const result = MessageSchema.safeParse(value)
  if (result.success) {
    return result.data as MarketMessage
  }
  return null
}
